USE `feedlot`;

#Clear Tables
SET SQL_SAFE_UPDATES = 0;
DELETE FROM USERS;
DELETE FROM ROLES;
DELETE FROM HERD_LOCALE_MAP;
DELETE FROM HERD_SUPPLIERS_MAP;
DELETE FROM SUPPLIER;
DELETE FROM LOCALE;
DELETE FROM HERD;
DELETE FROM FARM;
SET SQL_SAFE_UPDATES = 1;

#Seed USER data
#Seed FARM Table
INSERT INTO FARM
VALUES (1,'Holz Bros.');
INSERT INTO FARM
VALUES (2,'Person Farms');
INSERT INTO FARM
VALUES (3,'Muir Farms');
#Seed USERS
INSERT INTO USERS
VALUES (1,'JHolz', 'James', 'Holz', 'jtholzbeef@gmail.com', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.',1, 1);
INSERT INTO USERS
VALUES (2,'HHolz', 'Howard', 'Holz', 'howard@gmail.com', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.',1, 1);
#Seed ROLES Table
INSERT INTO ROLES
VALUES ('JHolz','ADMIN');
INSERT INTO ROLES
VALUES ('JHolz','DEFAULT');
INSERT INTO ROLES
VALUES ('HHolz','DEFAULT');

#Seed HERDS ETC
#Seed HERD
INSERT INTO HERD
VALUES (1, 1, 500, 600, 140, 'HOLZ1', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (2, 1, 200, 800, 150, 'HOLZ2', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (3, 1, 50, 800, 120, 'HOLZ3', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (4, 1, 700, 700, 180, 'HOLZ4', NOW(), NOW(), NOW(), NOW());
#Seed SUPPLIER
INSERT INTO SUPPLIER
VALUES (1, 'Bob Huggins');
INSERT INTO SUPPLIER
VALUES 	(2, 'Ray Ramano');
#Seed Supplier map
INSERT INTO HERD_SUPPLIERS_MAP
VALUES (1, 1, 1);
INSERT INTO HERD_SUPPLIERS_MAP
VALUES (2, 1, 2);
INSERT INTO HERD_SUPPLIERS_MAP
VALUES (3, 2, 3);
INSERT INTO HERD_SUPPLIERS_MAP
VALUES (4, 2, 4);
#Seed Locale
INSERT INTO LOCALE
VALUES (1, 1, 'Home Place SW');
INSERT INTO LOCALE
VALUES (2, 1, 'Home Place NW');
INSERT INTO LOCALE
VALUES (3, 1, 'Home Place New Shed');
INSERT INTO LOCALE
VALUES (4, 1, 'South Place');
#Seed Locale Herd Mapping
INSERT INTO HERD_LOCALE_MAP
VALUES (1, 1, 1, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (2, 2, 2, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (3, 3, 3, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (4, 4, 4, NOW());


#SELECT * FROM USERS;
#SELECT * FROM ROLES;
#SELECT * FROM HERD_LOCALE_MAP;
#SELECT * FROM HERD_SUPPLIERS_MAP;
#SELECT * FROM SUPPLIER;
#SELECT * FROM LOCALE;
#SELECT * FROM HERD;
#SELECT * FROM FARM;