USE `feedlot`;

#Seed USER data
#Seed FARM Table
INSERT INTO FARM
VALUES (1,'Holz Bros.');
INSERT INTO FARM
VALUES (2,'Person Farms');
INSERT INTO FARM
VALUES (3,'Muir Farms');
#Seed USERS
INSERT INTO USERS
VALUES (1,'JHolz', 'James', 'Holz', 'jtholzbeef@gmail.com', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.',1, 1);
INSERT INTO USERS
VALUES (2,'HHolz', 'Howard', 'Holz', 'howard@gmail.com', '$2a$10$EblZqNptyYvcLm/VwDCVAuBjzZOI7khzdyGPBr08PpIi0na624b8.',1, 1);
#Seed ROLES Table
INSERT INTO ROLES
VALUES ('JHolz','Admin');
INSERT INTO ROLES
VALUES ('JHolz','Default');
INSERT INTO ROLES
VALUES ('HHolz','Default');

#Seed HERDS ETC
#Seed HERD
INSERT INTO HERD
VALUES (1, 1, 500, 600, 140, 'HOLZ1', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (2, 1, 200, 800, 150, 'HOLZ2', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (3, 1, 50, 800, 120, 'HOLZ3', NOW(), NOW(), NOW(), NOW());
INSERT INTO HERD
VALUES (4, 1, 700, 700, 180, 'HOLZ4', NOW(), NOW(), NOW(), NOW());
#Seed SUPPLIER
INSERT INTO SUPPLIER
VALUES (1, 'Bob Huggins','Algona, IA',1);
INSERT INTO SUPPLIER
VALUES 	(2, 'Ray Ramano', 'Fort Worth Texas',1);
#Seed Locale
INSERT INTO LOCALE
VALUES (1, 1, 'Home Place SW');
INSERT INTO LOCALE
VALUES (2, 1, 'Home Place NW');
INSERT INTO LOCALE
VALUES (3, 1, 'Home Place New Shed');
INSERT INTO LOCALE
VALUES (4, 1, 'South Place');
#Seed Locale Herd Mapping
INSERT INTO HERD_LOCALE_MAP
VALUES (1, 1, 1, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (2, 1, 2, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (3, 1, 3, NOW());
INSERT INTO HERD_LOCALE_MAP
VALUES (4, 4, 4, NOW());

#Seed FEEDING ETC
#Seed FEED_TYPES
INSERT INTO FEED_TYPES
VALUES(1,1,"Corn");
INSERT INTO FEED_TYPES
VALUES(2,1,"Beans");
INSERT INTO FEED_TYPES
VALUES(3,1,"Oats");
INSERT INTO FEED_TYPES
VALUES(4,1,"Hay");
#Seed FEED_STOCK
INSERT INTO FEED_STOCK
VALUES(1,1,3000);
INSERT INTO FEED_STOCK
VALUES(2,2,300);
INSERT INTO FEED_STOCK
VALUES(3,3,3000);
INSERT INTO FEED_STOCK
VALUES(4,4,3000);
